global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
        # - alertmanager: 9093

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "zipkin"
    static_configs:
      - targets: ['zipkin-server:9411']

  # --- Infrastructure ---
  - job_name: "eureka"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["eurekaserver:8070"]

  - job_name: "config"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["configserver:8071"]

  - job_name: "gateway"
    metrics_path: "/actuator/prometheus"
    # 💡 [핵심] 게이트웨이가 HTTPS를 쓰면 여기도 반드시 https여야 합니다!
    scheme: "https"
    tls_config:
      # 💡 [무결성] 사설 인증서나 자체 서명 인증서라도 무조건 통과시킵니다.
      insecure_skip_verify: true
    static_configs:
      - targets: [ "gatewayserver:8072" ]

  # --- Auth & User ---
  - job_name: "auth"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["authserver:8090"]

  # --- Core Business Services ---
  - job_name: "product"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["productserver:8989"] # 💡 도커포트는 8081이지만 내부통신은 8989

  - job_name: "inventory"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "inventoryserver:8989" ]

  - job_name: "order"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["dseumorders:8989"] # 💡 내부 컨테이너 포트 8989 확인

  - job_name: "payment"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["dseumpayment:8083"]

  - job_name: "board"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["boardserver:8084"]

  # --- Specialized Services ---
  - job_name: "search"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["searchserver:8087"]

  - job_name: "rag"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ragserver:8099"]

  - job_name: "review"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "dseumreview:8098" ]
