spring:
  config:
    activate:
      on-profile: local
  cloud:
    vault:
      enabled: false
  elasticsearch:
    uris: ${RAG_ELASTICSEARCH_URIS:http://elasticsearch:9200}
  data:
    redis:
      host: ${RAG_REDIS_HOST:redis}
      port: ${RAG_REDIS_PORT:6379}
      password: ${RAG_REDIS_PASSWORD:1234}
