server:
  port: 8989

spring:
  application:
    name: dseum-inventory # 서비스 이름 식별

  # Config & Vault (Product 서버와 동일하게 유지)
  cloud:
    bootstrap:
      enabled: false
    compatibility-verifier:
      enabled: false
    function:
      definition: orderCheckedOutConsumer;paymentCompletedConsumer;paymentFailedConsumer;paymentCancelStatusConsumer;productCreatedConsumer
    stream:
      instance-count: ${STREAM_INSTANCE_COUNT:1}
      instance-index: ${STREAM_INSTANCE_INDEX:0}
      default:
        contentType: application/json
      bindings:
        orderCheckedOutConsumer-in-0:
          destination: OrderCheckedOut
          group: inventory-order-checked-out-group
          consumer:
            partitioned: true
        paymentCompletedConsumer-in-0:
          destination: PaymentCompleted
          group: inventory-payment-completed-group
          consumer:
            partitioned: true
        paymentFailedConsumer-in-0:
          destination: PaymentFailed
          group: inventory-payment-failed-group
          consumer:
            partitioned: true
        paymentCancelStatusConsumer-in-0:
          destination: PaymentCancelled
          group: inventory-payment-cancel-status-group
          consumer:
            partitioned: true
        productCreatedConsumer-in-0:
          destination: ProductCreated
          group: inventory-product-created-group
          consumer:
            partitioned: true
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092,kafka2:9092,kafka3:9092}
        bindings:
          orderCheckedOutConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-partitions: 1
              auto-commit-on-error: true
          paymentCompletedConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-partitions: 1
              auto-commit-on-error: true
          paymentFailedConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-partitions: 1
              auto-commit-on-error: true
          paymentCancelStatusConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-partitions: 1
              auto-commit-on-error: true
          productCreatedConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-partitions: 1
              auto-commit-on-error: true
    vault:
      host: dseum-vault
      port: 8200
      scheme: http
      authentication: TOKEN
      token: eum-root
      kv:
        enabled: true
        backend: secret

  config:
    import:
      - "optional:configserver:http://configserver:8071"
      - "optional:vault://"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
